export const GET_PACOTES_REQUEST = "GET_PACOTES_REQUEST";
export const GET_PACOTES = "GET_PACOTES";

export const POST_PACOTE_REQUEST = "POST_PACOTE_REQUEST";
export const POST_PACOTE = "POST_PACOTE";

export const UPDATE_PACOTE_REQUEST = "UPDATE_PACOTE_REQUEST";
export const UPDATE_PACOTE = "UPDATE_PACOTE";

export const DELETE_PACOTE_REQUEST = "DELETE_PACOTE_REQUEST";
export const DELETE_PACOTE = "DELETE_PACOTE";