export const GET_PAGAMENTO_REQUEST = "GET_PAGAMENTO_REQUEST";
export const GET_PAGAMENTO = "GET_PAGAMENTO";

export const POST_PAGAMENTO_REQUEST = "POST_PAGAMENTO_REQUEST";
export const POST_PAGAMENTO = "POST_PAGAMENTO";