export const GET_PASSEIOS_REQUEST = "GET_PASSEIOS_REQUEST";
export const GET_PASSEIOS = "GET_PASSEIOS";

export const POST_PASSEIO_REQUEST = "POST_PASSEIO_REQUEST";
export const POST_PASSEIO = "POST_PASSEIO";

export const UPDATE_PASSEIO_REQUEST = "UPDATE_PASSEIO_REQUEST";
export const UPDATE_PASSEIO = "UPDATE_PASSEIO";

export const DELETE_PASSEIO_REQUEST = "DELETE_PASSEIO_REQUEST";
export const DELETE_PASSEIO = "DELETE_PASSEIO";