export const GET_RESERVA_REQUEST = "GET_RESERVA_REQUEST";
export const GET_RESERVA = "GET_RESERVA";

export const POST_RESERVA_REQUEST = "POST_RESERVA_REQUEST";
export const POST_RESERVA = "POST_RESERVA";

export const DELETE_RESERVA_REQUEST = "DELETE_RESERVA_REQUEST";
export const DELETE_RESERVA = "DELETE_RESERVA";

