export const GET_LOGIN_REQUEST = "GET_LOGIN_REQUEST";
export const GET_LOGIN = "GET_LOGIN";
export const GET_LOGIN_FAIL = "GET_LOGIN_FAIL";

export const POST_REGISTER_REQUEST = "POST_REGISTER_REQUEST";
export const POST_REGISTER = "POST_REGISTER";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER = "GET_USER";

export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS = "GET_USERS";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER = "UPDATE_USER";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER = "DELETE_USER";
